name: express-jest-report-slack

on: 
  push:
    branches: [main]

jobs:

  test1:
    runs-on: ubuntu-latest
    name: express-jest-slack
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16  
      - name: express-jest-slack-my-action
        uses: youssefshibl/jest-report-in-stack-action@main
        with:
          slack_token: ${{ secrets.slack_token }}
          channel_id: ${{ secrets.slack_channel_id}}
